### PR TITLE
Test PR IV: A New Hope (For Benchmarks)

### PR DESCRIPTION
**Pull request by jrevels**
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/033600cd9eca3bf13c4f8b041c64650b5d70dc8d/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250191696) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/5ec11288a35da57e87ab95b54440c9a5f71c9af6/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250452246) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/4168328c47eac4cde8d60c1ec729548643c81d9b/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/jrevels/julia/pull/6#issuecomment-250531303): `NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")`
Logs and partial data can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/2e5720c286d3c448c88cd95c42e47019b7a90205/234b24e_vs_0287a99/report.md)
cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250532812) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/2212b15b0809d090eb5a953a6d6f0b4f4b6d971a/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250556640) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/6c1799dbb48f40eee6742477b1dc56c85f348b15/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250603551) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/9a422c306aeabd3f276b934697eb1b93253c3474/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250728635) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/0d689bc66676a5b1a3316390f28b08fd1a3c6ca3/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/jrevels/julia/pull/6#issuecomment-250746858): `NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")`
Logs and partial data can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/ae487f2cd4723a5a37e0a7b450f4435fa546e71a/234b24e_vs_0287a99/report.md)
cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/jrevels/julia/pull/6#issuecomment-250772352): `NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")`
Logs and partial data can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/86fe55e0544698daafa46ec6bd31618e15d8ca94/234b24e_vs_0287a99/report.md)
cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250781032) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/57a854906313c1149453760fe46b72bdb3b0c7c5/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250813821) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/73b2852d033da39ebfc80f81896f22f43fdfbe65/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks("factorization", vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250840453) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/0b54283e6957acfaf707f11119cb5c21291ca44f/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250935118) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/a1f19c3610b3e3d64d13342673a4709fc8d2b41e/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250940871) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/6b4b6ee9bdbb9134a71bd41021fad237422a34cc/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250966891) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/f53d6eaf8dd2736c7c5dc709052e35b8294cd9c2/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250971006) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/40c581652b7ca2cd89954bd6e5b1e2389aa97d64/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by jrevels** [comment]
@nanosoldier runbenchmarks(ALL, vs = ":master")

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250975772) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/c3dfa22a03a2b8a825d3ef1d663ffe65ab2d38a4/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-250975798) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/2aff8de01f5a34bdd8898ef2456710694c470133/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-251091944) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/73108bc5abc972b8e2f908d1c556950a0aa36ab6/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = :master)`

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = :master)`

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-251166387) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/2c2faa2988ace328206d893163be1f0447eac1c9/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild=true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-251240176) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/343f5953ce42ce19681f928ecd2c19817345e201/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-251264470) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/a485d84fd66b3fa628b895d5de2eb6b450b8d67d/f6b1e53_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/6#issuecomment-257978406) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/1c465ce569be6fac85b2c10676b7456df16d1c95/234b24e_vs_0287a99/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", isdaily = true, skipbuild = true)`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/jrevels/julia/pull/6#issuecomment-258012912):

```
NanosoldierError: error when preparing/pushing to report repo: KeyError("judged")
```

Unfortunately, the logs could not be uploaded.
cc @jrevels

**Pull request closed without merging**
