### PR TITLE
Test PR III: Revenge of the Nanosoldier

### PR DESCRIPTION
**Pull request by jrevels**

### CODE REVIEW

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by jrevels** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-218488382) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/b8702c4e6f32e0463f4328105401da00df44fdab/a087e6f/a087e6f_vs_c9d4051.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by jrevels** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-218565737) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/e336b913e168ce65bd15c8544fb029da47c99364/e8972d3/e8972d3_vs_c9d4051.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by jrevels** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-220181031) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/b5232a73593bbcc01f07872ba138baf9017dad27/a087e6f/a087e6f_vs_c9d4051.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks("array" && !("linalg"), vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-224360284) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/2158b669319e5a10b430bb2357b1e8869d6b3296/c7e1f17_vs_3142819/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-225053667) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/0004f889e8a703db7176442ca4333274d35c7e09/c7e1f17_vs_3142819/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-225601415) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/f4302dfc4c84b0b2e0de7bcfc68537edebc74dad/e8972d3_vs_3142819/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by jrevels** [comment]
Actually, that previous submission accidentally pulled in the old test branch...I've updated it, let's run again:

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-238344667) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/1e5029d5a2ac77635d74f92f014686d8b5b3e93e/fe563e1_vs_189a604/report.md). cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-238353291) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/525f7f723921db3532834d3ff25d41211cf20140/fe563e1_vs_189a604/report.md). cc @jrevels

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks("string", vs = ":master", skipbuild = true)`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/jrevels/julia/pull/5#issuecomment-238630144) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/jrevels/BaseBenchmarkReports/blob/c584062acecec0add9f4f373a937884c0c0a0780/e8972d3_vs_189a604/report.md). cc @jrevels

**Pull request closed without merging**
